notifications:
  email: false

dist: trusty
language: c
compiler: gcc

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "nathan-lg-github"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lcov libcmocka0 libcmocka-dev

before_script:
  # CMake
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make clean

script:
  - make
  # Build with SonarCloud
  - build-wrapper-linux-x86-64 --out-dir bw_output make
  - file ./CICDTest
  - make CICD_coverage
  - cd ..
  - sonar-scanner