notifications:
  email: false

language: c

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version

before_script:
  - export CC=arm-linux-gnueabihf-gcc
  - mkdir build
  - cd build
  - cmake ..

script: make