language: c
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target neat