notifications:
  email: false

dist: trusty
language: c
compiler: gcc

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "nathan-lg-github"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version

before_script:
  - export CC=arm-linux-gnueabihf-gcc
  - mkdir build
  - cd build
  - build-wrapper-linux-x86-64 --out-dir bw_output cmake ..
  - sonar-scanner

script: make