notifications:
  email: false

dist: trusty
language: c
compiler: gcc

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "nathan-lg-github"

before_install:
  # ARM Compilation
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  - export CC=arm-linux-gnueabihf-gcc

before_script:
  # CMocka
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - cd cmocka && mkdir build && cd build
  - cmake .. && make -j2 && sudo make install
  - cd ../..
  # CMake
  - mkdir build
  - cd build
  - cmake ..
  - make clean

script:
  # Build with SonarCloud
  - build-wrapper-linux-x86-64 --out-dir bw_output make
  - cd ..
  - sonar-scanner